# Generated by Django 4.1.1 on 2022-10-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
    ]
